application:
  name: nixmodules
  notifications:
    slack:
      channel: audit
  releaseChannels:
    - name: canary
      constants:
        - name: name
          string:
            value: canary
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
        - name: goval
          runtime: marine-cycle-160323--goval
      protections:
        - ref:
            name: check-no-datadog-alerts
            parameters:
              - name: apiKey
                secret:
                  secretRef:
                    key: datadogApiKey
                    version: datadogApiKey-0
              - name: appKey
                secret:
                  secretRef:
                    key: datadogAppKey
                    version: datadogAppKey-0
              - name: tagList
                string: "prodvana-monitor:nixmodules"
          lifecycle:
            - postDeployment:
                checkDuration: 600s
    - name: tarpit
      constants:
        - name: name
          string:
            value: tarpit
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: global
      constants:
        - name: name
          string:
            value: global
      preconditions:
        - manualApproval: {}
        - releaseChannelStable:
            releaseChannel: canary
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: hacker
      constants:
        - name: name
          string:
            value: hacker
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: teams
      constants:
        - name: name
          string:
            value: teams
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: asia-a
      constants:
        - name: name
          string:
            value: asia-a
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: asia-b
      constants:
        - name: name
          string:
            value: asia-b
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: staging
      constants:
        - name: name
          string:
            value: staging
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    # regional goval
    - name: prerelease
      constants:
        - name: name
          string:
            value: prerelease
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: picard
      constants:
        - name: name
          string:
            value: picard
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: riker
      constants:
        - name: name
          string:
            value: riker
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: kirk
      constants:
        - name: name
          string:
            value: kirk
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: spock
      constants:
        - name: name
          string:
            value: spock
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: worf
      constants:
        - name: name
          string:
            value: worf
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: janeway
      constants:
        - name: name
          string:
            value: janeway
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: sisko
      constants:
        - name: name
          string:
            value: sisko
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: pike
      constants:
        - name: name
          string:
            value: pike
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: wesley
      constants:
        - name: name
          string:
            value: wesley
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: block-us-central1
      constants:
        - name: name
          string:
            value: block-us-central1
      preconditions:
        - releaseChannelStable:
            releaseChannel: prerelease
        - sharedManualApproval:
            name: prod-wave-rg
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
