apiVersion: batch/v1
kind: Job
metadata:
  name: test-templates
  namespace: ansible
  labels:
    component: 'template-tester'
    cost-center: 'devex'
    environment: 'development'
spec:
  template:
    metadata:
      labels:
        component: 'template-tester'
        cost-center: 'devex'
        environment: 'development'
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      restartPolicy: Never
      containers:
        - name: template-tester
          image: nixos/nix
          command: ['scripts/test_templates.py']
          volumeMounts:
            - mountPath: /code
              name: code
          workingDir: /code/nixmodules
      initContainers:
        - args:
            - "--ssh"
            - "--repo=git@github.com:replit/nixmodules.git"
            - "--root=/code"
            - "--branch=th-tmpl-tests"
            - "--one-time"
            - "--depth=1"
            - "-dest=nixmodules"
            - "-timeout=320"
          image: "gcr.io/google_containers/git-sync:v3.1.5"
          name: git-sync
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /code
              name: code
            - mountPath: /etc/git-secret
              name: deploy-key
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 250m
              memory: 1Gi
      volumes:
        - emptyDir: {}
          name: code
        - name: deploy-key
          secret:
            defaultMode: 256
            secretName: git-ro-key
  ttlSecondsAfterFinished: 3600 # 1h
  backoffLimit: 1
