[worker.oci]
  enabled = false

[worker.containerd]
  enabled = true
  namespace = "docker"
  platforms = ["linux/amd64", "linux/amd64/v2", "linux/amd64/v3"]

  [worker.containerd.runtime]
    name = "@replitShimRunc@/bin/replit-shim-runc"
