name: checks
run-name: Spot check for errors
on:
  - push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: scripts/ci_check.sh
